### ISSUE TITLE
Speak the Code

### ISSUE THREAD

**Issue by JordynD** [JordynD/components-on-a-grid#3]
[Stash & Co..m4a.zip](https://github.com/JordynD/components-on-a-grid/files/7245497/Stash.Co.m4a.zip)
 @thatkidmadrid

**Comment by thatkidmadrid** [comment]
Looks and sounds really good!
```
header > img {
  grid-column: 1/-1;
  grid-row: 1;
  grid-area: banner;
}
```
As we went over in class, above you have `grid-column` and `grid-row` competing with `grid-area` to position the `img`. In your case, the banner is written last, so that's what the browser uses; it's overriding what the `grid-column/row` are trying to do.

I also notice you're explicitly using the `>` a lot to directly select some child elements which is fine, but it's not really necessary unless you have a lot of other elements on the page that it could be confused with. In all instances of this in your code, you can remove the `>` and it should behave the same.

Other than that, you were able to match the reference so full marks 👍
